services:

  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - USERS_SERVICE_URL=http://service_users:8000
      - ORDERS_SERVICE_URL=http://service_orders:8000
    networks:
      - app-network
    depends_on:
      - service_users
      - service_orders
    restart: unless-stopped

  service_users:
    build: ./service_users
    environment:
      - NODE_ENV=production
      - PORT=8000
    networks:
      - app-network
    restart: unless-stopped

  service_orders:
    build: ./service_orders
    environment:
      - NODE_ENV=production
      - PORT=8000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
